import { Menu } from "@/types/menu";

const menuData: Menu[] = [
  {
    id: 1,
    title: "Inicio",
    submenu: [
      {
        id: 101,
        title: "Nosotros",
        path: "/about",
        newTab: false,
      },
      {
        id: 102,
        title: "Metodología",
        path: "/metodologia",
        newTab: false,
      },
      {
        id: 103,
        title: "Casos de éxito",
        path: "/casos-de-exito",
        newTab: false,
      },
      {
        id: 104,
        title: "Blog",
        path: "/blog",
        newTab: false,
      },
      {
        id: 105,
        title: "Servicios",
        path: "/servicios",
        newTab: false,
      },
      {
        id: 106,
        title: "Contacto",
        path: "/contact",
        newTab: false,
      },
      {
        id: 107,
        title: "Aviso de Privacidad",
        path: "/privacidad",
        newTab: false,
      }
    ],
    newTab: false,
  },
  {
    id: 2,
    title: "Soluciones IA",
    newTab: false,
    submenu: [
      {
        id: 201,
        title: "Agente IA de Marketing",
        path: "/agentes-ia/marketing",
        newTab: false,
      },
      {
        id: 202,
        title: "Agente IA de Turismo y Hotelería",
        path: "/agentes-ia/turismo-hoteleria",
        newTab: false,
      },
      {
        id: 203,
        title: "Agente IA de Ventas",
        path: "/agentes-ia/ventas",
        newTab: false,
      },
      {
        id: 204,
        title: "Agente IA de Seguros",
        path: "/agentes-ia/seguros",
        newTab: false,
      },
      {
        id: 205,
        title: "Agente IA para Retail y E-commerce",
        path: "/agentes-ia/retail-ecommerce",
        newTab: false,
      },
      {
        id: 206,
        title: "Agente IA de Ciberseguridad",
        path: "/agentes-ia/ciberseguridad",
        newTab: false,
      },
      {
        id: 207,
        title: "Agente IA de Educación",
        path: "/agentes-ia/educacion",
        newTab: false,
      },
      {
        id: 208,
        title: "Agente IA de BackOffice",
        path: "/agentes-ia/backoffice",
        newTab: false,
      },
      {
        id: 209,
        title: "Agente IA de Finanzas",
        path: "/agentes-ia/finanzas",
        newTab: false,
      },
      {
        id: 210,
        title: "Agente IA de Logística",
        path: "/agentes-ia/logistica",
        newTab: false,
      },
      {
        id: 211,
        title: "Agente IA de Agricultura",
        path: "/agentes-ia/agricultura",
        newTab: false,
      },
      {
        id: 212,
        title: "Agente IA de Recursos Humanos",
        path: "/agentes-ia/recursos-humanos",
        newTab: false,
      },
      {
        id: 213,
        title: "Agente IA de Industria Legal",
        path: "/agentes-ia/industria-legal",
        newTab: false,
      },
      {
        id: 214,
        title: "Agente IA de WhatsApp",
        path: "/agentes-ia/whatsapp",
        newTab: false,
      },
      {
        id: 215,
        title: "IA para análisis de datos y automatización",
        path: "/soluciones/analisis-datos-automatizacion",
        newTab: false,
      },
      {
        id: 216,
        title: "Automatización con IA: procesos más rápidos",
        path: "/soluciones/automatizacion-con-ia",
        newTab: false,
      },
      {
        id: 217,
        title: "RPA estratégico para flujos operativos",
        path: "/soluciones/rpa-estrategico",
        newTab: false,
      },
      {
        id: 218,
        title: "Tableros ejecutivos en tiempo real",
        path: "/soluciones/tableros-ejecutivos",
        newTab: false,
      },
      {
        id: 219,
        title: "Monitoreo de KPIs y alertas inteligentes",
        path: "/soluciones/monitoreo-kpis",
        newTab: false,
      },
      {
        id: 220,
        title: "Sistema multi-agente IA",
        path: "/marketing/sistema-multiagente-ia",
        newTab: false,
      },
      {
        id: 221,
        title: "Atención al cliente con IA conversacional",
        path: "/marketing/atencion-cliente-ia",
        newTab: false,
      },
      {
        id: 222,
        title: "IA para ventas y cierre comercial",
        path: "/marketing/ia-para-ventas",
        newTab: false,
      },
      {
        id: 223,
        title: "Automatización de embudos y nurturing",
        path: "/marketing/embudos-automatizados",
        newTab: false,
      },
      {
        id: 224,
        title: "Segmentación predictiva de audiencias",
        path: "/marketing/segmentacion-predictiva",
        newTab: false,
      },
      {
        id: 225,
        title: "Consultoría estratégica en IA",
        path: "/desarrollo/consultoria-estrategica-ia",
        newTab: false,
      },
      {
        id: 226,
        title: "Modelos de IA a la medida",
        path: "/desarrollo/modelos-a-medida",
        newTab: false,
      },
      {
        id: 227,
        title: "Integración de IA con sistemas empresariales",
        path: "/desarrollo/integracion-sistemas",
        newTab: false,
      },
      {
        id: 228,
        title: "Mantenimiento y soporte continuo",
        path: "/desarrollo/soporte-continuo",
        newTab: false,
      },
      {
        id: 229,
        title: "Laboratorio de innovación IA",
        path: "/desarrollo/laboratorio-innovacion",
        newTab: false,
      },
    ],
  },
  {
    id: 3,
    title: "Industrias",
    newTab: false,
    submenu: [
      {
        id: 301,
        title: "Turismo y Hotelería",
        path: "/industrias/turismo-hoteleria",
        newTab: false,
      },
      {
        id: 302,
        title: "Seguros",
        path: "/industrias/seguros",
        newTab: false,
      },
      {
        id: 303,
        title: "Retail y E-commerce",
        path: "/industrias/retail-ecommerce",
        newTab: false,
      },
      {
        id: 304,
        title: "Educación",
        path: "/industrias/educacion",
        newTab: false,
      },
      {
        id: 305,
        title: "Finanzas",
        path: "/industrias/finanzas",
        newTab: false,
      },
      {
        id: 306,
        title: "Logística",
        path: "/industrias/logistica",
        newTab: false,
      },
      {
        id: 307,
        title: "Agricultura",
        path: "/industrias/agricultura",
        newTab: false,
      },
      {
        id: 308,
        title: "Recursos Humanos",
        path: "/industrias/recursos-humanos",
        newTab: false,
      },
      {
        id: 309,
        title: "Industria Legal",
        path: "/industrias/legal",
        newTab: false,
      },
    ],
  },
  {
    id: 4,
    title: "Recursos",
    newTab: false,
    submenu: [
      {
        id: 401,
        title: "Centro de documentación",
        path: "/recursos/documentacion",
        newTab: false,
      },
      {
        id: 402,
        title: "Preguntas frecuentes",
        path: "/recursos/faq",
        newTab: false,
      },
      {
        id: 403,
        title: "Webinars y eventos",
        path: "/recursos/webinars",
        newTab: false,
      },
      {
        id: 404,
        title: "Partners tecnológicos",
        path: "/recursos/partners",
        newTab: false,
      },
      {
        id: 405,
        title: "Contacto comercial",
        path: "/contact",
        newTab: false,
      },
    ],
  },
];
export default menuData;
